version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes: 
      - /home/lio/Documentos/devel/00Docker/volumen/postgresdb:/var/lib/postgresql/data

    ports: 
      - 5432:5432